version: "3.8"

services:
  # Base de Datos NoSQL
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  # Aplicación Backend
  backend:
    build: ./backend
    container_name: backend_app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/bitacora
    depends_on:
      - mongodb
    networks:
      - app-network

  # Aplicación Frontend
  frontend:
    build: ./frontend
    container_name: frontend_app
    ports:
      - "5173:5173"
    stdin_open: true
    tty: true
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
